#!/usr/bin/env python3

import platform
import os
import sys
import shutil

#script for running matches/tournaments using the official runner/scripts.
#goal is to mimic actual tournament running conditions as closely as possible

#hardcoded stuff ############################################################################
botsPath = "./bots/" #relative path to bots from script position

#global vars ################################################################################
verbosity = 2 #verbosity 0 = fast as possible; 1 = show only game map; 2 = show as much as possible
bot1 = ''
bot2 = ''

#function defs###############################################################################
def showUsage():
    print("Usage: runMatches [-v0|-v1|-v2] bot1 bot2 ...")
    print("       runs matches between bots")
    print("       bot1, bot2 etc are folder names of bots in " + botsPath)
    print("       -v specifies verbosity (with 0 being least verbose)")

def parseArgs():
    global verbosity
    global bot1
    global bot2

    if(len(sys.argv) < 2):
        showUsage()
        exit()

    #defaults
    verbosity = 2
    bot1 = sys.argv[1]
    bot2 = sys.argv[2]

    if("-v" in sys.argv[1]):
        bot1 = sys.argv[2]
        bot2 = sys.argv[3]
        if(sys.argv[1] == "-v0"):
            verbosity = 0
        elif(sys.argv[1] == "-v1"):
            verbosity = 1
        else:
            verbosity = 2

def copy(src, dest):
    try:
        shutil.copytree(src, dest, ignore=shutil.ignore_patterns('rounds'))
    except OSError as e:
        # If the error was caused because the source wasn't a directory
        if e.errno == shutil.errno.ENOTDIR:
            shutil.copy(src, dest)
        else:
            print('Directory not copied. Error: %s' % e)

#the script  ###############################################################################

parseArgs()
print("bot1: " + bot1 + ", bot2: " + bot2 + ", verbosity: " + str(verbosity))

if(bot1 == bot2):
    bot2 = (bot1 + "_autogenerated_copy")
    tempCopyDest = botsPath + bot2
    print("bot1 == bot2.  Creating copy in " + tempCopyDest)
    copy(botsPath + bot1, tempCopyDest)

#put in bot names
gameRunnerConfigFile = "./starter-pack/game-runner-config.json"
file = open(gameRunnerConfigFile + ".original", "r")
lines = file.readlines()
file.close()

for i, line in enumerate(lines):
    if("player-a" in line):
        lines[i] = "\"player-a\": \"../" + botsPath + bot1 + "\",\n"
    if("player-b" in line):
        lines[i] = "\"player-b\": \"../" + botsPath + bot2 + "\",\n"
    if("verbose-mode" in line):
        if(verbosity == 0):
            lines[i] = "\"verbose-mode\": false,\n"
        else:
            lines[i] = "\"verbose-mode\": true,\n"

file = open(gameRunnerConfigFile, "w")
file.writelines(lines)
file.close()

print("Game runner modified.  Starting match.")
print("")

os.chdir("starter-pack")
if(platform.system() == 'Windows'):
    os.system("run.bat")
elif(platform.system() == 'Linux'):
    if(verbosity < 2):
        os.system("make run | grep -v -e [a-z=]")
    else:
        os.system("make run")
