#!/usr/bin/env python3

import platform
import os
import sys
import shutil

#script for running matches/tournaments using the official runner/scripts.
#goal is to mimic actual tournament running conditions as closely as possible

#hardcoded stuff #############################
_botsPath = "./bots/" #relative path to bots from script position

#global vars #################################
_verbosity = 2 #verbosity 0 = fast as possible; 1 = show only game map; 2 = show as much as possible
_bot1 = ''
_bot2 = ''

#function defs################################
def showUsage():
    print("Usage: runMatches [-v0|-v1|-v2] bot1 bot2 ...")
    print("       runs matches between bots")
    print("       bot1, bot2 etc are folder names of bots in " + _botsPath)
    print("       -v specifies verbosity (with 0 being least verbose)")

def parseArgs():
    global _verbosity
    global _bot1
    global _bot2

    if(len(sys.argv) < 2):
        showUsage()
        exit()

    #defaults
    _verbosity = 2
    _bot1 = sys.argv[1]
    _bot2 = sys.argv[2]

    if("-v" in sys.argv[1]):
        _bot1 = sys.argv[2]
        _bot2 = sys.argv[3]
        if(sys.argv[1] == "-v0"):
            _verbosity = 0
        elif(sys.argv[1] == "-v1"):
            _verbosity = 1
        else:
            _verbosity = 2

def copy(src, dest):
    try:
        shutil.copytree(src, dest, ignore=shutil.ignore_patterns('rounds'))
    except OSError as e:
        # If the error was caused because the source wasn't a directory
        if e.errno == shutil.errno.ENOTDIR:
            shutil.copy(src, dest)
        else:
            print('Directory not copied. Error: %s' % e)

#puts in bot1 and bot2 into the game runner config file
def addBotNamesToConfig(bot1, bot2):
    gameRunnerConfigFile = "./starter-pack/game-runner-config.json"
    originalGameRunnerConfigFile = gameRunnerConfigFile + ".original"

    if not os.path.isfile(originalGameRunnerConfigFile):
        shutil.copy(gameRunnerConfigFile, originalGameRunnerConfigFile)

    file = open(gameRunnerConfigFile + ".original", "r")
    lines = file.readlines()
    file.close()

    for i, line in enumerate(lines):
        if("player-a" in line):
            lines[i] = "\"player-a\": \"../" + _botsPath + bot1 + "\",\n"
        if("player-b" in line):
            lines[i] = "\"player-b\": \"../" + _botsPath + bot2 + "\",\n"
        if("verbose-mode" in line):
            if(_verbosity == 0):
                lines[i] = "\"verbose-mode\": false,\n"
            else:
                lines[i] = "\"verbose-mode\": true,\n"

    file = open(gameRunnerConfigFile, "w")
    file.writelines(lines)
    file.close()

def confirmDir(file):
    if not os.path.isdir(file):
        print("Can't find " + file)
        return False
    return True

#the script  ###############################################################################

parseArgs()
print("bot1: " + _bot1 + ", bot2: " + _bot2 + ", verbosity: " + str(_verbosity))

#sanity checks
if (not confirmDir(_botsPath + _bot1)) or (not confirmDir(_botsPath + _bot2)):
    exit()

#make a copy of the bot folder if this is a match between the same bot
if(_bot1 == _bot2):
    _bot2 = (_bot1 + "_autogenerated_copy")
    tempCopyDest = _botsPath + _bot2
    print("bot1 == bot2.  Creating copy in " + tempCopyDest)
    copy(_botsPath + _bot1, tempCopyDest)

addBotNamesToConfig(_bot1, _bot2)

print("Game runner modified.  Starting match.")
print("")

os.chdir("starter-pack")
if(platform.system() == 'Windows'):
    os.system("run.bat")
elif(platform.system() == 'Linux'):
    if(_verbosity < 2):
        os.system("make run | grep -v -e [a-z=]")
    else:
        os.system("make run")
