#include "DigCommand.hpp"
#include "DoNothingCommand.hpp"
#include "ShootCommand.hpp"
#include "TeleportCommand.hpp"
#include "BananaCommand.hpp"
#include "SnowballCommand.hpp"
#include "SelectCommand.hpp"